[package]
name = "tokio-socketcan"
version = "0.1.3"
authors = ["Terry Kerr <root@oefd.ca>"]
edition = "2018"
description = "Asynchronous Linux SocketCAN sockets with tokio"
license = "MIT"
repository = "https://github.com/oefd/tokio-socketcan"

[dependencies]
socketcan = "1.7"
futures= { version = "0.3" }
futures-util = { version = "0.3" }
tokio-net = "0.2.0-alpha.6"
mio = "0.6"
libc = "0.2"

[dev-dependencies]
async-std = { version = "1.0", features = ["attributes"] }
futures-timer = { version = "2.0" }
